name: Report Coverage

on:
  workflow_run:
    workflows: ["Vitest"]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.TOKEN_FOR_ACTION }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
